title = "My New Hugo Site"
languageCode = "en-us"
baseurl = "http://replace-this-with-your-hugo-site.com/"

# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-86507992-1"

# Define how many posts should appear on a site
paginate = 10

[params.sidebar]
    # Replace the avatar with a picture of your own under static/images
    avatar = "avatar.jpg"
    # Use Markdown to format the string. This works nearly all over the theme
    bio = "**I'm Topher**, a web developer & customer success enthusiast"
    # The icons will be shown if you enter your username
    twitter = "tophs_mcgoats"
    github = "chammz"
    dribbble = ""
    facebook = ""
    googleplus = ""
    flickr = ""
    linkedin = ""

    copyright = [
      "&copy; John Doe",
      "Design: [HTML5 UP](//html5up.net)",
      "Demo Images: [Unsplash](//unsplash.com/)"
    ]


[[menu.main]]
  name = "Home"
  url  = "/"
  weight = 0

[[menu.main]]
  name = "Blog"
  url  = "post/"
  weight = 10

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 0

[[menu.main]]
    name = "About"
    url  = "about"
    weight = 5

[[menu.main]]
    name = "Blog"
    url  = "post/"
    weight = 10