baseurl = "/"
title = "My New Hugo Site"
languageCode = "en-us"
theme = "hugo-strata-theme"
disqusShortname = "spf13"

# Enable Google Analytics by inserting your tracking code
googleAnalytics = "UA-86507992-1"

# Define how many posts should appear on a site
paginate = 10

[params]
	# To provide some metadata for search engines feel free to add a few
    # information about you and your website.
	name = "Your name"
	description = "Describe your website"

	# Format dates with Go's time formatting
	date_format = "2006-01-02"

	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []

[params.sidebar]
    # Replace the avatar with a picture of your own under static/images
    avatar = "Little_chris_headdart.jpg"
    # Use Markdown to format the string. This works nearly all over the theme
    bio = "**I'm Topher**, a web developer & customer success enthusiast"
    # The icons will be shown if you enter your username
    twitter = "tophs_mcgoats"
    github = "chammz"
    dribbble = ""
    facebook = ""
    googleplus = ""
    flickr = ""
    linkedin = ""

	[params.about]
		hide  = false
		title = "Learning to Code, One Step at a Time"
    	content = "I am currently enrolled as a student in Bloc's Web Developer Track, an apprenticeship style program that pairs students with an experienced developer. I'm currently learning Javascript"


	[params.portfolio]
		hide  = false
		title = "Projects"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."


[[menu.main]]
  name = "Home"
  url  = "/"
  weight = 0

[[menu.main]]
  name = "Blog"
  url  = "post/"
  weight = 10

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 0

[[menu.main]]
    name = "About"
    url  = "about"
    weight = 5

[[menu.main]]
    name = "Blog"
    url  = "post/"
    weight = 10